### ISSUE TITLE
Tenant names need to be updated/clarified

### ISSUE THREAD

**Issue by shanecribbs** [LODSCloudSlice/AZ-104T00-A-Microsoft-Azure-Administrator-No-Azure-Pass-Required-#13]
# Issue Details

In this cloudslice lab, the tenant names need to be updated/clarified.  For example, the lab references "default tenant" which isn't appropriate for cloudslice.   Several attendees switched to the "cloudslice" tenant to attempt to add the guest user.  Update references to either the ContosoLab or FirstAAD tenant.

# Issue Location

Manage Azure Active Directory Identities
Lab 1 (Module 1)

# Issue Screenshot (if applicable):

## Additional Information:

**Comment by ZekeStarr** [comment]
Hi Shane,

We've updated the LODS Cloudslice labs (Module 01 in particular) to reference 'First AAD' instead of 'Default Tenant' where appropriate.

Thank you for sending this our way.
