### ISSUE TITLE
Update lab title

### ISSUE THREAD

**Issue by shanecribbs** [LODSCloudSlice/AZ-104T00-A-Microsoft-Azure-Administrator-No-Azure-Pass-Required-#14]
# Issue Details

Lab title indicates "No Azure Pass Required" but the lab does indeed require an Azure Pass or subscription provided by the learner.  Please update the title to indicate the lab cannot be run without an Azure Pass so it is known BEFORE launching the lab.

# Issue Location

Manage Subscriptions and RBAC
AZ-104T00-A Microsoft Azure Administrator [No Azure Pass Required], Module 02A

# Issue Screenshot (if applicable):

**Comment by LODSAdmin** [comment]
Thank you for reaching out.  We certainly strive to be transparent and make known any limitations in being able to offer a full azure pass solution.   We surface any such limitations in the following manners:

1.  On the course description itself, we ensure awareness is raised in advance: 
![image](https://user-images.githubusercontent.com/83987197/133444200-c0dcb566-708d-4705-bf23-e34fe8a226eb.png)

2.  We have a section under our Important Course Information, that outlines limitation and can be launched from the class page: 
![image](https://user-images.githubusercontent.com/83987197/133445267-223c90c9-6077-4656-af6b-f67e01500e45.png)

3. In the labs themselves, an alert should be surfaced that advises when a lab cannot be completed fully with a CS solution.  


Thank you for your feedback and reaching out to us. We hope the above helps clarify.

**Comment by shanecribbs** [comment]
Thanks, but this still doesn't address the main issue.  The learner does not know which labs will not be available to complete in the cloudslice environment until AFTER they launch it, and 2 minutes later finally are able to see the alert.  Simply noting this in the lab title/description seems to be an easy answer.  Thanks.
