### ISSUE TITLE
Lab does not work

### ISSUE THREAD

**Issue by shanecribbs** [LODSCloudSlice/AZ-104T00-A-Microsoft-Azure-Administrator-No-Azure-Pass-Required-#15]
# Issue Details

Lab fails to work as expected, which appears to be due to overly restrictive cloudslice policies.

# Issue Location

Manage Governance via Azure Policy 
AZ-104T00-A Microsoft Azure Administrator [No Azure Pass Required], Module 02B (CSS)

Task 2 doesn't work as expected.  The storage account fails to be created even when using the tags required by the policy.  Also the error is not as you would normally see for a failed tag policy.  It appears that some restrictions on the cloudslice environment are to stringent.

Task 3 doesn't work as the learner gets an error when creating a remediation task on the policy.  It appears that some restrictions on the cloudslice environment are to stringent.

# Issue Screenshot (if applicable):

**Comment by LODSAdmin** [comment]
Thanks for letting us know! 

For this one, you will need to add a tag with a name of **ms-resource-usage** and a value of **azure-cloud-shell** in order to validate.

**Comment by LODSAdmin** [comment]
@shanecribbs we preformed the necessary corrections to fix this issue.
