### ISSUE TITLE
Resource Group already exists

### ISSUE THREAD

**Issue by shanecribbs** [LODSCloudSlice/AZ-104T00-A-Microsoft-Azure-Administrator-No-Azure-Pass-Required-#16]
# Issue Details

Steps say to create a Resource Group that already exists.  It appears that to avoid cloudslice policy restrictions, the resource group has already been created for the learner.  If the regular steps indicate to create the Resource Group, can we loosen the cloudslice policy and removed the pre-staged resource group?  If not, please update the steps to match the modified environment.

# Issue Location

Manage Azure resources by Using ARM Templates (Expected Duration 40 minutes, 0 seconds)
AZ-104T00-A Microsoft Azure Administrator [No Azure Pass Required], Module 03B (CSR)

Task 2
Step 4

# Issue Screenshot (if applicable):

**Comment by LODSAdmin** [comment]
Thank you for reporting, this one has been fixed.
