### ISSUE TITLE
Resource Group Already Exists, again

### ISSUE THREAD

**Issue by shanecribbs** [LODSCloudSlice/AZ-104T00-A-Microsoft-Azure-Administrator-No-Azure-Pass-Required-#17]
# Issue Details

Step 5 asks us to run commands to create a Resource Group, but it gives an error the Resource Group already exists.  Either remove step or remove Resource Group and policy blocking Resource Group creation.

# Issue Location

Implement Intersite Connectivity (Expected Duration 45 minutes, 0 seconds)
AZ-104T00-A Microsoft Azure Administrator [No Azure Pass Required], Module 05 (CSR)
Task 1, Step 5

# Issue Screenshot (if applicable):

**Comment by LODSAdmin** [comment]
@shanecribbs  we have removed the extraneous references. Thanks again for reporting!
