### ISSUE TITLE
NSG creation not allowed

### ISSUE THREAD

**Issue by shanecribbs** [LODSCloudSlice/AZ-104T00-A-Microsoft-Azure-Administrator-No-Azure-Pass-Required-#18]
# Issue Details

Policy prevents us from creating NSG.  Has follow on effects in later tasks.

# Issue Location
Implement Virtual Networking (Expected Duration 1 hours, 30 minutes)
AZ-104T00-A Microsoft Azure Administrator [No Azure Pass Required], Module 04 (CSR)
Task 4, Step 5

# Issue Screenshot (if applicable):

**Comment by LODSAdmin** [comment]
We are currently unable to reproduce this one.  Can you provide a screenshot of the error?
![image](https://user-images.githubusercontent.com/83987197/133476321-455a9a97-99c6-44d9-bfc0-10d40ccd2bdd.png)

**Comment by shanecribbs** [comment]
I tried to re-create the problem and can't as creating the NSG works for me as well.  I had multiple students with the same error message yesterday that referred to the NSG creation failing due to policy.  Well....I guess it works for now.  (shrug).  Thanks.
